34233.9 <c-29#201> Created logger
34233.9 <c-29#201> appl_initialize was called
34233.9 <c-29#201:7> Logger was updated
34233.9 <c-29#201:7> Started intializing cube lib
34233.9 <c-29#201:7> Finished intializing cube lib with worker, starting to work
34234 <c-29#201:7> requestCubes => [62] Buffer size: 0
34234 <c-29#201:7> Sent requestCubes signal to root
34234 <c-29#201:7> Received 1 cubes from root
34234 <c-29#201:7> The main loop continues
34234 <c-29#201:7> Started solving a cube
34353.7 <c-29#201:7> Cube failed
34353.7 <c-29#201:7> Added failed cube
34353.7 <c-29#201:7> returnFailedCubes => [62] Buffer size: 3
34353.7 <c-29#201:7> Sent 1 failed cubes to root
34353.7 <c-29#201:7> Received receivedFailedCubes signal from root
34353.8 <c-29#201:7> requestCubes => [62] Buffer size: 0
34353.8 <c-29#201:7> Sent requestCubes signal to root
34353.8 <c-29#201:7> Received 1 cubes from root
34353.8 <c-29#201:7> The main loop continues
34353.8 <c-29#201:7> Started solving a cube
34497 <c-29#201:7> appl_interrupt was called
34497 <c-29#201:7> Interrupting worker
34497 <c-29#201:7> appl_interrupt was called
34497 <c-29#201:7> appl_withdraw was called
34497 <c-29#201:7> Started withdraw thread
34497 <c-29#201:7> STOP (0.00s since last cb)
34497 <c-29#201:7> Solving interrupted
34497 <c-29#201:7> The main loop continues
34497 <c-29#201:7> Leaving the main loop due to an interruption
34497 <c-29#201:7> Finished withdrawing lib
34497 <c-29#201:7> Enter destructor of CubeWorker
34497 <c-29#201:7> Time waiting for messages: 0.000
34497 <c-29#201:7> Enter destructor of CubeWorkerInterface
34497 <c-29#201:7> Enter destructor of CubeRoot
34497 <c-29#201:7> Finished withdraw thread
34559.7 <c-29#201:7> Enter destructor
34559.7 <c-29#201:7> Time working: 263.062
34559.7 <c-29#201:7> Time suspended: 0.000
34559.7 <c-29#201:7> Joined cleanup thread
34559.7 <c-29#201:7> Exit destructor
34559.7 <c-29#201:7> Destructing logger
