48063.9 <c-14#280> Created logger
48064 <c-14#280> appl_initialize was called
48064 <c-14#280:4> Logger was updated
48064 <c-14#280:4> Started intializing cube lib
48064 <c-14#280:4> Finished intializing cube lib with worker, starting to work
48067.2 <c-14#280:4> requestCubes => [28] Buffer size: 0
48067.2 <c-14#280:4> Sent requestCubes signal to root
48067.2 <c-14#280:4> Received 1 cubes from root
48067.2 <c-14#280:4> The main loop continues
48067.2 <c-14#280:4> Started solving a cube
48444.5 <c-14#280:4> Cube failed
48444.5 <c-14#280:4> Added failed cube
48444.5 <c-14#280:4> returnFailedCubes => [28] Buffer size: 5
48444.5 <c-14#280:4> Sent 1 failed cubes to root
48444.5 <c-14#280:4> Received receivedFailedCubes signal from root
48444.5 <c-14#280:4> requestCubes => [28] Buffer size: 0
48444.5 <c-14#280:4> Sent requestCubes signal to root
48444.5 <c-14#280:4> Received 1 cubes from root
48444.5 <c-14#280:4> The main loop continues
48444.5 <c-14#280:4> Started solving a cube
48520.1 <c-14#280:4> appl_interrupt was called
48520.1 <c-14#280:4> Interrupting worker
48520.1 <c-14#280:4> appl_interrupt was called
48520.1 <c-14#280:4> appl_withdraw was called
48520.1 <c-14#280:4> Started withdraw thread
48520.9 <c-14#280:4> STOP (1.42s since last cb)
48520.9 <c-14#280:4> Solving interrupted
48520.9 <c-14#280:4> The main loop continues
48520.9 <c-14#280:4> Leaving the main loop due to an interruption
48520.9 <c-14#280:4> Finished withdrawing lib
48520.9 <c-14#280:4> Enter destructor of CubeWorker
48520.9 <c-14#280:4> Time waiting for messages: 0.000
48522.1 <c-14#280:4> Enter destructor of CubeWorkerInterface
48522.1 <c-14#280:4> Enter destructor of CubeRoot
48522.2 <c-14#280:4> Finished withdraw thread
48581.3 <c-14#280:4> Enter destructor
48581.3 <c-14#280:4> Time working: 456.066
48581.3 <c-14#280:4> Time suspended: 0.000
48581.3 <c-14#280:4> Joined cleanup thread
48581.3 <c-14#280:4> Exit destructor
48581.3 <c-14#280:4> Destructing logger
