53315.8 <c-20#310> Created logger
53315.8 <c-20#310> appl_initialize was called
53315.8 <c-20#310:2> Logger was updated
53315.8 <c-20#310:2> Started intializing cube lib
53315.8 <c-20#310:2> Finished intializing cube lib with worker, starting to work
53315.8 <c-20#310:2> requestCubes => [48] Buffer size: 0
53315.8 <c-20#310:2> Sent requestCubes signal to root
53315.8 <c-20#310:2> Received 1 cubes from root
53315.8 <c-20#310:2> The main loop continues
53315.8 <c-20#310:2> Started solving a cube
53366.7 <c-20#310:2> Cube failed
53366.7 <c-20#310:2> Added failed cube
53366.7 <c-20#310:2> returnFailedCubes => [48] Buffer size: 5
53366.7 <c-20#310:2> Sent 1 failed cubes to root
53366.7 <c-20#310:2> Received receivedFailedCubes signal from root
53366.7 <c-20#310:2> requestCubes => [48] Buffer size: 0
53366.7 <c-20#310:2> Sent requestCubes signal to root
53366.7 <c-20#310:2> Received 1 cubes from root
53366.7 <c-20#310:2> The main loop continues
53366.7 <c-20#310:2> Started solving a cube
53553 <c-20#310:2> appl_interrupt was called
53553 <c-20#310:2> Interrupting worker
53553 <c-20#310:2> appl_interrupt was called
53553 <c-20#310:2> appl_withdraw was called
53553 <c-20#310:2> Started withdraw thread
53553 <c-20#310:2> STOP (0.00s since last cb)
53553 <c-20#310:2> Solving interrupted
53553 <c-20#310:2> The main loop continues
53553 <c-20#310:2> Leaving the main loop due to an interruption
53553 <c-20#310:2> Finished withdrawing lib
53553 <c-20#310:2> Enter destructor of CubeWorker
53553 <c-20#310:2> Time waiting for messages: 0.000
53553 <c-20#310:2> Enter destructor of CubeWorkerInterface
53553 <c-20#310:2> Enter destructor of CubeRoot
53553 <c-20#310:2> Finished withdraw thread
53613.7 <c-20#310:2> Enter destructor
53613.7 <c-20#310:2> Time working: 237.223
53613.7 <c-20#310:2> Time suspended: 0.000
53613.7 <c-20#310:2> Joined cleanup thread
53613.7 <c-20#310:2> Exit destructor
53613.7 <c-20#310:2> Destructing logger
