19991.7 <c-30#120> Created logger
19991.7 <c-30#120> appl_initialize was called
19991.7 <c-30#120:4> Logger was updated
19991.7 <c-30#120:4> Started intializing cube lib
19991.7 <c-30#120:4> Finished intializing cube lib with worker, starting to work
19992 <c-30#120:4> requestCubes => [52] Buffer size: 0
19992 <c-30#120:4> Sent requestCubes signal to root
19992 <c-30#120:4> Received 1 cubes from root
19992 <c-30#120:4> The main loop continues
19992 <c-30#120:4> Started solving a cube
19992 <c-30#120:4> Cube failed
19992 <c-30#120:4> Added failed cube
19992 <c-30#120:4> returnFailedCubes => [52] Buffer size: 3
19992 <c-30#120:4> Sent 1 failed cubes to root
19992 <c-30#120:4> Received receivedFailedCubes signal from root
19992 <c-30#120:4> requestCubes => [52] Buffer size: 0
19992 <c-30#120:4> Sent requestCubes signal to root
19992 <c-30#120:4> Received 1 cubes from root
19992 <c-30#120:4> The main loop continues
19992 <c-30#120:4> Started solving a cube
20949.1 <c-30#120:4> appl_interrupt was called
20949.1 <c-30#120:4> Interrupting worker
20949.1 <c-30#120:4> appl_interrupt was called
20949.1 <c-30#120:4> appl_withdraw was called
20949.1 <c-30#120:4> Started withdraw thread
20949.1 <c-30#120:4> STOP (0.04s since last cb)
20949.1 <c-30#120:4> Solving interrupted
20949.1 <c-30#120:4> The main loop continues
20949.1 <c-30#120:4> Leaving the main loop due to an interruption
20949.1 <c-30#120:4> Finished withdrawing lib
20949.1 <c-30#120:4> Enter destructor of CubeWorker
20949.1 <c-30#120:4> Time waiting for messages: 0.000
20949.2 <c-30#120:4> Enter destructor of CubeWorkerInterface
20949.2 <c-30#120:4> Enter destructor of CubeRoot
20949.2 <c-30#120:4> Finished withdraw thread
21010.1 <c-30#120:4> Enter destructor
21010.1 <c-30#120:4> Time working: 957.404
21010.1 <c-30#120:4> Time suspended: 0.000
21010.1 <c-30#120:4> Joined cleanup thread
21010.1 <c-30#120:4> Exit destructor
21010.1 <c-30#120:4> Destructing logger
