9172.03 <c-10#56> Created logger
9172.36 <c-10#56> appl_initialize was called
9172.36 <c-10#56:11> Logger was updated
9172.36 <c-10#56:11> Started intializing cube lib
9172.36 <c-10#56:11> Finished intializing cube lib with worker, starting to work
9178.98 <c-10#56:11> requestCubes => [41] Buffer size: 0
9178.98 <c-10#56:11> Sent requestCubes signal to root
9178.98 <c-10#56:11> Received 1 cubes from root
9178.98 <c-10#56:11> The main loop continues
9178.98 <c-10#56:11> Started solving a cube
9453.97 <c-10#56:11> Cube failed
9453.97 <c-10#56:11> Added failed cube
9453.98 <c-10#56:11> returnFailedCubes => [41] Buffer size: 2
9453.98 <c-10#56:11> Sent 1 failed cubes to root
9453.98 <c-10#56:11> Received receivedFailedCubes signal from root
9453.99 <c-10#56:11> requestCubes => [41] Buffer size: 0
9453.99 <c-10#56:11> Sent requestCubes signal to root
9453.99 <c-10#56:11> Received 1 cubes from root
9453.99 <c-10#56:11> The main loop continues
9453.99 <c-10#56:11> Started solving a cube
9558.55 <c-10#56:11> appl_interrupt was called
9558.55 <c-10#56:11> Interrupting worker
9558.55 <c-10#56:11> appl_interrupt was called
9558.55 <c-10#56:11> appl_withdraw was called
9558.55 <c-10#56:11> STOP (0.00s since last cb)
9558.55 <c-10#56:11> Solving interrupted
9558.55 <c-10#56:11> The main loop continues
9558.55 <c-10#56:11> Leaving the main loop due to an interruption
9558.56 <c-10#56:11> Started withdraw thread
9558.56 <c-10#56:11> Finished withdrawing lib
9558.56 <c-10#56:11> Enter destructor of CubeWorker
9558.56 <c-10#56:11> Time waiting for messages: 0.002
9558.97 <c-10#56:11> Enter destructor of CubeWorkerInterface
9558.97 <c-10#56:11> Enter destructor of CubeRoot
9559.02 <c-10#56:11> Finished withdraw thread
9618.73 <c-10#56:11> Enter destructor
9618.73 <c-10#56:11> Time working: 386.188
9618.73 <c-10#56:11> Time suspended: 0.000
9618.73 <c-10#56:11> Joined cleanup thread
9618.73 <c-10#56:11> Exit destructor
9618.73 <c-10#56:11> Destructing logger
